apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
{{- with .Values.labels.redis  }}
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.redis_port }}
      targetPort: {{ .Values.service.redis_port }}
      protocol: TCP
      name: http
    {{- with .Values.labels.redis  }}
  selector:
    {{ toYaml . | nindent 4  }}
{{- end }}
    
