apiVersion: v1
kind: Service
metadata:
  name: home
  labels:
    {{- with .Values.labels.home }}
    {{- toYaml . | nindent 4  }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
      name: http
  selector:
    {{- with .Values.labels.home }}
    {{- toYaml . | nindent 4  }}
    {{- end }}
