apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{  .Values.volumeName  }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.volumeCapacity  }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.hostPath  }}"
