apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumepvclaimName  }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.volumeRequest  }}"