kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "jenkins.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name  }}
roleRef:
  kind: Role
  name: {{ include "jenkins.fullname" . }}
  apiGroup: rbac.authorization.k8s.io