name: Docker Image CI
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
    - name: Create docker tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Commit report
      run: |
          ls -R
          python3 k8s-crud-microservice/deploy/helm-charts/image-tag.py -i ${{ steps.vars.outputs.sha_short }}
          git config --global user.name 'vishnuswmech'
          git config --global user.email 'vishnuanand97udt@gmail.com'
          git commit -am "Image tag updation"
          git push
