name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
    - name: Create docker tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}    
    - name: Build and push the Home Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./k8s-crud-microservice/build/code/home/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-crud:${{ steps.vars.outputs.sha_short }}
